version: '2'
services:
  mysqlcontainer:
    container_name: my_mysql_container
    build: ./mysql
  phpcontainer:
    container_name: my_php_container
    build: ./php
    ports: 
      - "8888:80"
    depends_on:
      - mysqlcontainer
