# This is just a comment.
FROM mongo
MAINTAINER Pello Altadill

# With this, we plan to use data/db as external storage
VOLUME ["/data/db"]

# This sets working dir for RUN, CMD, ENTRYPOINT, COPY and ADD
WORKDIR /data

EXPOSE 27017:27017

